### ISSUE TITLE
Milestone 3 Server side

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/proof-of-attendance#10]
Tasks for milestone 3: 

- [ ] Authentication that ensures only event managers can mint.
- [ ] create an event manager account.
- [ ] Endpoint for minting the token to each corresponding accountIds.
- [ ] Connect frontend mint button with server minting endpoint.

**Comment by mrrobot16** [comment]
Tasks for milestone 4:

1.  Create authentication that ensures only event managers can mint.
Discuss with Cameron for greenlight potential solutions: 
2.  Create event manager functionality through a master account that has the authority to create other event managers.
