### ISSUE TITLE
Launch preparations

### ISSUE THREAD

**Issue by RenierC** [dOrgTech/proof-of-attendance#35]
## Todo

- [ ] Remove dead & unreachable code **(applies to front-end, back-end, and contract)**.
- [ ] Clean non relevant console logs **(applies to front-end, back-end, and contract)**
- [ ] Set up new mainnet account
- [ ] Switch all references to mainnet, _as a heads up there are many places in the code with hardcoded Testnet accounts_ **(applies to front-end, back-end, and contract)**
- [ ] Check the deployed server's config with mainnet (especially that its using the main net rpcs) 
- [ ] Validate or set up the final IPFS account or service the client is gonna use
